sudo: true
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

script:
- cmake -H. -B_build 
- cmake --build _build
- cd _build
- ./pack pack
- ./unpack pack
